
spring:
  datasource:
    url: jdbc:postgresql://mahmud.db.elephantsql.com/ttavwthq
    username: ttavwthq
    password: CoRdZ2dcYLEOXppiajE95ne3VLIWSSSk
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
jwt:
  key: vszC!+%d(H:OAwJ./20G0~tnJ]VX'+fN
server:
  port: ${PORT:8080}